# Generated by Django 4.1.7 on 2023-03-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_sale_customer_saleperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='salePerson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='crm.sale'),
        ),
    ]
