# Generated by Django 4.1.7 on 2023-03-06 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_customer_saleperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('domain', models.CharField(max_length=240)),
                ('department', models.CharField(max_length=240)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.RemoveField(
            model_name='sale',
            name='department',
        ),
        migrations.AlterField(
            model_name='sale',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='crm.team'),
        ),
    ]
