# Generated by Django 4.1.7 on 2023-03-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_team_remove_sale_department_alter_sale_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(db_index=True, max_length=240, unique=True),
        ),
        migrations.AlterModelTable(
            name='sale',
            table='sales',
        ),
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
    ]
